
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Flask: Debug (8080)",
      "type": "python",
      "request": "launch",
      "module": "flask",
      "env": {
        "FLASK_APP": "app.py",        // メインのファイル名に合わせる
        "FLASK_ENV": "development"
      },
      "args": [
        "run",
        "--host=127.0.0.1",
        "--port=8080"
      ],
      "jinja": true
    }
  ]
}
